[package]
name = "git-wt"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "git-wt"
path = "src/main.rs"

[profile.release]
lto = "thin"

[dependencies]
clap = { version = "4", features = ["derive"] }
git2 = { version = "0.21", features = ["ssh", "https"] }
anyhow = "1"
rpassword = "7"
ssh-key = { version = "0.6", features = ["encryption", "ed25519", "rsa", "ecdsa"] }
owo-colors = "4"

[dev-dependencies]
tempfile = "3"
